Stage1
petuum/adaptdl pull request #115
Opened 2022-04-04 10:32 UTC by Xuezhi-Liang

<img width="829" alt="Unknown" src="https://user-images.githubusercontent.com/11881183/161203614-c1f43be7-7078-4de8-802d-cfe7ff7a397e.png">

Notes: 

1. The first step is to create the Context class and start to move the core AdaptDL mathematics into that class. 

2. The AdaptiveDataLoader should get refactored to use the Context class for those AdaptDL logic to prevent duplication of logic. 

3. But the changes to AdaptiveDataLoader are purely implementation changes, users of the class shouldn't need to see any difference.

2022-04-06 19:44 UTC, aurickq requested changes

2022-04-06 19:44 UTC, aurickq commented on adaptdl/adaptdl/torch/context.py
> +        self._elastic = adaptdl.torch.data.AdaptiveDataLoaderHelper(batch_size)
Should make sure the `AdaptiveDLContext` class does not depend on the `AdaptiveDataLoaderHelper` class (or anything related to PyTorch).

2022-04-06 19:44 UTC, aurickq commented on adaptdl/adaptdl/torch/context.py
> +                                          self._elastic._state.accumulation_steps))
Shouldn't do any cross-replica synchronization from a call to the `AdaptiveDLContext` class. The synchronization should happen outside, from the callsite.

2022-04-06 19:44 UTC, aurickq commented on adaptdl/adaptdl/torch/context.py
> +        self._elastic.to_tensorboard(writer, global_step, tag_prefix)
Tensorboard isn't core AdaptDL logic so shouldn't be included in this class.

2022-04-06 19:44 UTC, aurickq commented on adaptdl/adaptdl/torch/context.py
> +from adaptdl.torch.scaling_rules import ScalingRuleBase
Should make sure this module doesn't depend on anything from PyTorch

2022-04-06 19:44 UTC, aurickq commented on adaptdl/adaptdl/torch/context.py
> +class AdaptiveDLContext(object):
Maybe rename it to just `Context` so usage of it can be simply `adaptdl.Context`

2022-05-31 12:43 UTC, Xuezhi-Liang commented
close via a new PR #123

2022-05-31 12:43 UTC, closed without merging