Using jsonpatch and podpreset to accept clsuter config
petuum/adaptdl pull request #62
Opened 2020-10-27 22:45 UTC by TairuiWang

all tests passed on internal cluster

2020-10-27 22:47 UTC, TairuiWang commented
@aurickq ready for review

2020-10-30 01:30 UTC, aurickq requested changes

2020-10-30 01:30 UTC, aurickq commented on helm/adaptdl-sched/values.yaml
> +  #   containerPatch: "[{\"op\": \"add\", \"path\": \"/env/0\", \"value\": {\"name\": \"NCCL_SOCKET_IFNAME\", \"value\": \"net1\"}}]"
I think the example could just be written in-line as YAML, which makes writing this section a bit more readable, like
```
- op: add
  path: "/metadata/annotations/k8s.v1.cni.cncf.io~1networks"
  value: "macvlan-conf"
```

2020-10-30 01:30 UTC, aurickq commented on helm/adaptdl-sched/templates/config.yaml
> +  {{- end }}
Split into two env vars: `ADAPTDL_JOB_PATCH_PODS` and `ADAPTDL_JOB_PATCH_CONTAINERS` referring to `.Values.job.patch.pods` and `.Values.job.patch.containers`, respectively.

2020-10-30 01:30 UTC, aurickq commented on sched/adaptdl_sched/controller.py
> +    def _pod_update(self, pod):
Use a more descriptive name, like `_patch_pod_and_containers`

2020-10-30 04:13 UTC, aurickq requested changes

2020-10-30 04:13 UTC, aurickq commented on helm/adaptdl-sched/templates/config.yaml
> +  ADAPTDL_JOB_POD_PATCH : {{ .Values.job.patch.pods | toJson | quote }}
`ADAPTDL_JOB_PATCH_PODS`

2020-10-30 04:13 UTC, aurickq commented on sched/adaptdl_sched/config.py
> +def get_job_container_patch():
Keep getter names matching env var names: `get_job_patch_pods()` and `get_job_patch_containers()`

2020-10-30 19:24 UTC, merged